# Generated by Django 3.0.2 on 2020-01-31 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterwatchapp', '0006_auto_20180729_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coronavirus',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
                ('CountryProvince', models.CharField(max_length=100)),
                ('NoOfConfirmed', models.IntegerField()),
                ('NoOfRecovered', models.IntegerField()),
                ('NoOfDeath', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Coronavirus',
            },
        ),
    ]
